name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Hangi branch'e push yapıldığında çalışacak?
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17' # JDK 17 olarak değiştirildi
          distribution: 'temurin'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: target/*.jar